version: '3.8'

services:
  backend:
    build: ./SIAO-backend
    container_name: siao-backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      JWT_SECRET: secret_desenvolvimento
      CORS_ORIGIN: http://localhost:5173
    volumes:
      - ./SIAO-backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./SIAO-frontend
    container_name: siao-frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3000
    volumes:
      - ./SIAO-frontend:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - backend